name: pipeline

on:

  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



# env:
#   CI: false


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm setup
        run: npm ci



      - name: Build
        run: npm run build


  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm setup
        run: npm ci


      - name: Test
        run: npm test

  build-push-docker-Image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t durgaprasad81/calculator-docker-image:latest

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push durgaprasad81/calculator-docker-image:latest
  deploy:
    needs: build-push-docker-Image
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: docker pull durgaprasad81/calculator-docker-image:latest
      - name: Stop running calculator-docker-image
        run: docker stop calculator-docker-image || true
      - name: Start new container
        run: docker run --name calculator-spe -d -p 3000:3000 durgaprasad81/calculator-docker-image:latest
      - name: Clean up unused containers
        run: docker system prune -af